### PR TITLE
feat:[#108] blackbox rescue shell to host

### LINKED ISSUE #108: shortcut for host shell
### Feature Description

This is a good idea if you are the type of person to mess up VSO pico (me) or want to access abroot without booting up the vso subsystem or other Miscellaneous stuff

### Rationale

I love messing with my abroot so much, that I'm tired of waiting for libpod to close when rebooting

also adb/fastboot/mtkclient/SP Flash tool works better outside of vso pico

### Additional Information

the desktop file:
```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=true
Exec=/usr/bin/bash
Name=Rescue Terminal
Comment=Use this when something is stopping you from resetting VSO or when wanting to access the system shell. This does not guarantee any full write access to root.
Icon=org.gnome.Console
Categories=ConsoleOnly;System;
StartupWMClass=kgx
```

### PR DESCRIPTION
**Pull request by jardon**
- add shell detect script
- add rescue action to blackbox desktop
- change blackbox custom override to shell detect script

closes #108

### CODE REVIEW

**Comment by jardon** [comment]
@kbdharun I'll have to recheck, but this doesnt currently work it seems as the desktop file doesnt get put in its location during the build process.

adding that desktop file to `~/local/share/applications` does behave appropriately.

am i missing something to get that desktop file included in the build?

**Comment by jardon** [comment]
and if theres a better way to do this through the gsettings schema override, im happy to tweak it, but the documentation either doesnt exist or is very hard to find through search tools

**Comment by taukakao** [comment]
Yeah, I fought with this a while back. I think the problem is that installing Blackbox overrides this file. 
So you have to rename it to something else and replace the original blackbox file after installing it.

There's a big second problem with this tho that I've noticed. If you are inside blackbox and open a second terminal with Ctrl+Shift+N it will open the "rescue shell" which is not ideal and will confuse users.

**Comment by jardon** [comment]
hmmm i thought the order there was reversed, but im probably wrong.  

thats a fair point that i havent looked at yet.  i tried to go the other way around, but if you set the custom command though the gsettings override, you cant pass the `-c` option successfully as it will spawn the host-shell though the vso-os-shell which would defeat the point of the rescue shell.

ill look the blackbox source and see what i can figure out

**Comment by jardon** [comment]
i would like to get this implemented somehow.  one of my biggest problems with vanilla in day to day usage is the occasional breakage of the the vso-os-shell and not having a convenient way to perform a rescue

**Comment by jardon** [comment]
what about installing kgx, removing the desktop file for it, and setting the rescue mode for blackbox to call kgx?

i know thats probably pretty weird, but from a UX perspective, it at least gets the user to something workable

but i could definitely see having blackbox open a different application being a no-go

**Comment by jardon** [comment]
if there was a way (and there might be) to disregard the gsettings override though the environment, that would be ideal

**Comment by taukakao** [comment]
I mean the reason why we use blackbox in the first place is because kgx didn't really work well with distrobox.

If we install kgx both on the host and in the container then there is not really a reason to stick to blackbox and we can just use kgx which is better in almost every regard and also the "vanilla" gnome tool.

Having a mix of blackbox and kgx makes the system unintuitive imo.

> if there was a way (and there might be) to disregard the gsettings override though the environment, that would be ideal

I think I remember checking that but didn't find anything.

**Comment by taukakao** [comment]
@axtloss 
That still has the problem that Ctrl+Shift+N opens a rescue shell no matter what shell the user is currently using.

**Comment by axtloss** [comment]
no it doesn't, it launches a vso shell by default because the command is the script without the rescue argument

**Comment by axtloss** [comment]
what would happen is that pressing Ctrl+shift+N when using the rescue shell would open vso, but that's not an issue imo

**Comment by taukakao** [comment]
@axtloss Ah, now I see what you meant.
It's a good idea but we can't pass different arguments to the script.
If the default shell is /usr/bin/some-script and we run `blackbox-terminal -c /usr/bin/some-script rescue` then blackbox will first run "some-script" and then "some-script rescue" from inside the vso shell.

But with environment variables it might work.
If we set the default shell to our script we can run:
blackbox-terminal
or
BLACKBOX_SHELL_OVERRIDE="/usr/bin/bash" blackbox-terminal

The first would start vso shell by default and the second would run the command in the environment variable.

**Comment by axtloss** [comment]
> If the default shell is /usr/bin/some-script and we run blackbox-terminal -c "/usr/bin/some-script rescue" then blackbox will first run "some-script" and then "some-script rescue" from inside the vso shell.

what about `blackbox-terminal -c rescue`

**Comment by taukakao** [comment]
> what about blackbox-terminal -c rescue

That would run the command "rescue" inside the vso shell.

**Comment by jardon** [comment]
It looks like we might be able to tweak the env with `GSETTINGS_SCHEMA_DIR` for the rescue action here if we point it to a schema that doesnt have the custom command override?

**Comment by taukakao** [comment]
@jardon That is true, but I think just having a script that either runs vso shell or bash depending on the environment variable is easier here.

**Comment by axtloss** [comment]
> > what about blackbox-terminal -c rescue
> 
> That would run the command "rescue" inside the vso shell.

how so? wouldn't it result in `vso-shell-script rescue` being ran which causes the script to open a shell on the host

**Comment by taukakao** [comment]
@axtloss 
Ah yeah, I assumed incorrectly how this was implemented. I checked and it does run:
`custom-script -c input`

I wrote this script to test it out:
```
#!/bin/bash
if [ $# -eq 0 ]
then
        exec /usr/bin/vso-os-shell
else
        exec "${SHELL-bash}" "$@"
fi
```

It works as expected. I would actually prefer running commands this way.
We can just do:
`blackbox-terminal`
to start it with vso-shell and
`blackbox-terminal -c bash`
to run a "rescue shell"

This would mean that everything you pass would be executed on the host-shell. Not sure if this is better or worse than running those in the vso shell, opinions?

**Comment by axtloss** [comment]
Yep that's what i meant, realised that the extra `rescue` option isn't really useful as you demonstrated already

**Comment by jardon** [comment]
Let me see if I understand yall correctly.  

1. the default behavior of blackbox is to open `/bin/bash`
2. providing a schema override can enable the default behavior to be altered.  in our case currently, its `vso-os-shell`
3. creating a custom script to pick between `bash` and `vso-os-shell`
4. we should point the override to the custom script
5. configure the normal blackbox behavior through a desktop file and also have a rescue mode

is that on track?

**Comment by axtloss** [comment]
just have a shell script that executes vso by default and if any argument to the script is given it executes that command on the host 
that allows for a separate desktop file that runs blackbox with `-c bash` which would open a bash shell on the host

**Comment by jardon** [comment]
so the issue that i see with this and in my testing, that doesnt fix the ctrl+shift+n behavior.  the only thing that ive been able to do to get the ctrl+shift+n behavior to work correctly is to use the glib override to pass either `vso-os-shell` or a script to pick `vso-os-shell` by default.  the issue with this is that it appears to override across the board.  so every instance of black box always runs that script, and there is no way to pass additional arguments to it.

**Comment by axtloss** [comment]
yeah, that's the point 
you're not supposed to pass arguments to it when creating a new tab, it's so that the `-c` argument works properly and lets us configure a rescue shell

**Comment by jardon** [comment]
im not sure we're on the same page.

1. the override allows the ctrl+shift+n functionality to work properly. 
2. i wrote a script that takes an arg and runs bash or takes no arg for vso-os-shell
3. i set the custom command in the override to point to that script
4. new terminal funcitonality works as expected.
5. what does not work is opening a rescue shell since the override wont let you pass an argument to the script

now if im wrong about any of that, im happy to fix it, but could you tell me which of those is my understanding incorrect?

**Comment by axtloss** [comment]
the override is set to the script which lets you specify the command to run with `blackbox -c <command>` which can be used for a rescue shell to run `blackbox -c bash`

**Comment by jardon** [comment]
yes, that is correct.  my point is you cant pass arguments to that script.

**Comment by axtloss** [comment]
you can pass arguments to that script with the -c flag in blackbox, tau tested that

**Comment by taukakao** [comment]
Ok, I think a writeup what is to be done will help here:

1. create the script (Let's call it /usr/bin/blackbox-command-proxy) with the contents:
```
#!/bin/bash
if [ $# -eq 0 ]
then
        exec /usr/bin/vso-os-shell
else
        exec "${SHELL-bash}" "$@"
fi
```

2. use the existing schema but instead of vso-os-shell, point it to:
```
[com.raggesilver.BlackBox]
use-custom-command = true
custom-shell-command = "/usr/bin/blackbox-command-proxy"
```

3. Adjust the desktop file from this PR to have:
`Exec=blackbox-terminal` (for default vso-shell)
and
`Exec=blackbox-terminal -c /usr/bin/bash` (for rescue shell)


The script then either recieves no arguments in which case it will just run vso shell or recieve "-c /usr/bin/bash" so it will run "/usr/bin/bash -c /usr/bin/bash" inside blackbox, leaving the user in the host shell.

**Comment by jardon** [comment]
okay i've updated it as described and it works :partying_face: 

i'm still not sure exactly how those args get passed through with the override, but i wont complain.  thanks for all the help  @taukakao and @axtloss !!

**Review by taukakao — APPROVED** [review]
Perfect, LGTM, thanks for implementing this. It's been really bugging me as well. Good team work. 

P.S. when you run "blackbox-terminal -c something" it will run the shell which is configured in the gschema and propagate the "-c something" arguments to that.

**Pull request merged**
