### PR TITLE
Added support for opening terminal in nautilus

### PR DESCRIPTION
**Pull request by fluoriteByte**
using https://github.com/Stunkymonkey/nautilus-open-any-terminal as the script, tag 0.6.0

### CODE REVIEW

**Comment by fluoriteByte** [comment]
from what i gleam from the logs, it seems to have skipped for some reason the module file i put there

**Comment by axtloss** [comment]
You still have to tell it to include the module in the recipe.yml file

**Comment by fluoriteByte** [comment]
oop lol

**Comment by fluoriteByte** [comment]
Do i have to explicitly add make as an apt dep for this module? I guessed it might be available because of earlier modules that had it

**Comment by axtloss** [comment]
technically it's not required, but it'd be better to have it in case earlier modules suddenly dont need it anymore

**Comment by fluoriteByte** [comment]
Do you know why it failed? Cus im pretty sure make only gets cleaned at the end

**Comment by axtloss** [comment]
https://github.com/Vanilla-OS/desktop-image/actions/runs/10327285133/job/28592228057?pr=201#step:12:8668
it cant find localization files, you have to run `make build install schema`

**Comment by axtloss** [comment]
Also change the commit title to `feat: add support for opening terminal in nautilus` (see the [contributor guidelines](https://github.com/Vanilla-OS/.github/blob/main/CONTRIBUTING.md#commits) for further reference)

**Review by axtloss — APPROVED** [review]

**Comment by axtloss** [comment]
Thanks for the contribution!

**Pull request merged**
