### PR TITLE
mitigates password leak by clearing file

### PR DESCRIPTION
**Pull request by taukakao**
This creates a systemd service and script which delete the /etc/org.vanillaos.FirstSetup.commands file which is containing the user password in old installs. 

Using something like shred was considered, but since Vanilla is using btrfs, this will not do anything useful. In fact, there is no way that I know of to reliably overwrite the blocks containing the file in btrfs so this will have to do. 

This is all contained within one module so that it can be deleted easily in the future. 

Module tested in custom image inside VM.

### CODE REVIEW

**Comment by axtloss** [comment]
Why isn't this a file in includes.container

**Comment by taukakao** [comment]
@axtloss 
> This is all contained within one module so that it can be deleted easily in the future.

I want this to be as self contained as possible

**Comment by axtloss** [comment]
apart from there not being any need for it to be self contained, the extra script is not necessary, the systemd unit can run the command to clear the file itself
putting it in a file like this just makes it more confusing

**Comment by taukakao** [comment]
It will be removed again soon so I want to make that as easy as possible, thus self contained. 
And I wasnt sure how arguments are handled by systemd but I will try it if I have the time. 

But it's a temporary solution so it's not that relevant imo.

**Comment by axtloss** [comment]
Why would we remove this? We have quite a lot of versions that are affected by this vulnerability and we can never be sure that everyone who's affected has updated their system.

**Pull request merged**
