### PR TITLE
fix: binder module not found

### LINKED ISSUE #112: Waydroid/binder module not working
### Issue Description

I can't use Waydroid at all, setup fails complaining `/dev/binderfs/binder-control` doesn't exist.

### Steps to Reproduce

As far as I can tell, it is caused by using Orchid with IBT enabled (11th gen intel or newer)

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

Attempting to mount `/dev/binderfs` mount crashes with a segfault, dmesg shows a missing `endbr` instruction. This is a security feature being triggered caused by the binder module not being compiled with the right options, see https://lwn.net/Articles/889475/

At a glance, it would appear the module should be compiled with `-fcf-protection=branch`, but i'm not sure how that needs to happen, nor if it's anbox's issue or an issue with dkms.

### PR DESCRIPTION
**Pull request by jardon**
the anbox-modules has been deprecated and archived.  this moves to the intree binder module

Potentially closes https://github.com/Vanilla-OS/vanilla-system-operator/issues/112

### CODE REVIEW

**Comment by jardon** [comment]
this can be moved to their repo once their packaging is updated.

related issue: https://github.com/waydroid/waydroid/issues/1484

**Comment by jardon** [comment]
saving this for later

https://docs.kernel.org/admin-guide/binderfs.html

**Comment by jardon** [comment]
it looks like for modules, we could either run this [helper](https://github.com/waydroid/waydroid/blob/main/tools/helpers/drivers.py) or just write a short script to do what that helper script does

**Comment by axtloss** [comment]
built in debian binder module doesn't work, this pr wouldn't really fix anything

**Comment by jardon** [comment]
Can you be more specific about how it doesn't work?

I'm not saying that you're wrong. I haven't been able to get waydroid working at all on vanilla so I can't exactly verify. So I'm just going off of if it loads and what waydroid does to configure on Debian

**Comment by axtloss** [comment]
It simply doesn't work, it shows as loaded but does not do anything.
Either way, I am reworking the way waydroid works, I dont see why we should put more effort intofixing an inherently broken way of doing it

**Comment by mirkobrombin** [comment]
Can we close this since the plan is to have a sysext?

**Pull request closed without merging**
